### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lukaf** [fanhattan/lua-resty-rate-limit#9]
Hi,

Is lack of license intentional? If not, would it be possible to add one?
Thank you!

**Comment by danielgpm** [comment]
I'm also curious about the license, as I would like to contribute by adding memcached support (instead of starting everything from scratch).  Suggestion: [MIT](http://choosealicense.com/licenses/mit/) will great ;)

**Comment by travisbell** [comment]
Hey guys, I've added an MIT license if you're still interested. Sorry it took me so long to get to this.
